export const SHOW_SNACKBAR = "SHOW_SNACKBAR";
export const HIDE_SNACKBAR = "HIDE_SNACKBAR";
export const RESET_SNACKBAR = "RESET_SNACKBAR";
export const SET_USER_DATA = "SET_USER_DATA";
export const FETCHING_PLAYBACK_DATA = "FETCHING_PLAYBACK_DATA";
export const SET_PLAYBACK_DATA = "SET_PLAYBACK_DATA";
export const SET_PLAYBACK_DATA_FAILED = "SET_PLAYBACK_DATA_FAILED";
export const SET_PLAYBACK_DATA_FAILED_INVALID_TOKEN =
  "SET_PLAYBACK_DATA_FAILED_INVALID_TOKEN";
export const NO_PLAYBACK_DATA = "NO_PLAYBACK_DATA";
