export const SHOW_SNACKBAR = "SHOW_SNACKBAR";
export const HIDE_SNACKBAR = "HIDE_SNACKBAR";
export const RESET_SNACKBAR = "RESET_SNACKBAR";
export const SET_USER_DATA = "SET_USER_DATA";
export const SET_PLAYBACK_DATA = "SET_PLAYBACK_DATA";
export const SET_PLAYBACK_DATA_FAILED = "SET_PLAYBACK_DATA_FAILED";
